export const colors = {
  'primary': '#fbc341',
  'white': '#ffffff',
  'black': '#000000'
};

const options = [
  {name: 'Yes', value: 'yes'},
  {name: 'No', value: 'no'},
  // {name: 'Other', value: 'other'},
];

const taOptions = [
  {name: 'ஆம்', value: 'yes'},
  {name: 'இல்லை', value: 'no'},
  // {name: 'மற்றவை', value: 'other'},
];

export const language = {
  en: {
    login: 'Login',
    register: 'Register',
    lorem20: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    skip: 'Skip',
    auth: 'Auth',
    chooseOne: 'Choose One',
    parent: 'Parent',
    physician: 'Physician',
    features: 'Features',
    dashboard: 'Dashboard',
    questionnaire: 'Questionnaire',
    onboarding: 'Onboarding',
    firstName: 'First Name',
    lastName: 'Last Name',
    babyName: 'Baby Name',
    babyDob: 'Baby Date of Birth',
    dob: 'Date of Birth',
    phoneNo: 'Phone Number',
    address: 'Address',
    prev: 'Prev',
    next: 'Next',
    submit: 'Submit',
    yes: 'Yes',
    no: 'No',
    other: 'Other',
    trust: 'Trust',
    waitForConfirmation: 'Wait for confirmation',
    alreadyRegistered: 'Already Registered',
    goBack: 'Go Back',
    goToLogin: 'Go to Login',
    retryAgain: 'Retry again',
    congrats: 'Congrats',
    sorry: 'Sorry',
    chat: 'Chat',
    logout: 'Logout',
    changeLang: 'Change Language',
    settings: 'Settings',
    password: 'Password',
    retypePassword: 'Retype Password',
    email: 'Email',
    specializedIn: 'Specialized In',
    home: 'Home',
    history: 'History',
    upcomingNotifications: 'Upcoming Notifications',
    noNotificaionsAvailable: 'No notifications available!',
    profile: 'Profile',
    company: 'Company',
    app: 'App',
    account: 'Account',
    appointments: 'Appointments',
    aboutUs: 'About Us',
    faq: 'F.A.Q.',
    termsConditions: 'Terms & Conditions',
    privacyPolicies: 'Privacy Policies',
    language: 'Language',
    aboutApp: 'About App',
    questions: [
      {question: 'What are some good questions to ask?', options },
      {question: 'What are 10 questions to ask?', options },
      {question: 'What are the 36 questions?', options },
      {question: 'What are some deep relationship questions?', options },
      {question: 'What questions can I ask my crush?', options },
      {question: 'What should I ask my gf?', options },
    ],
  },
  ta: {
    login: 'உள்நுழைய',
    register: 'பதிவு செய்ய',
    lorem20: 'லோரெம் இப்சம் என்பது அச்சிடுதல் மற்றும் தட்டச்சு செய்யும் துறையின் போலி உரை.',
    skip: 'தவிர்',
    auth: 'அங்கீகாரம்',
    chooseOne: 'ஒன்றை தேர்ந்தெடு',
    parent: 'பெற்றோர்',
    physician: 'மருத்துவர்',
    features: 'அம்சங்கள்',
    dashboard: 'டாஷ்போர்டு',
    questionnaire: 'கேள்வித்தாள்',
    onboarding: 'போர்ட்போர்டிங்',
    firstName: 'முதல் பெயர்',
    lastName: 'கடைசி பெயர்',
    babyName: 'குழந்தை பெயர்',
    babyDob: 'குழந்தை பிறந்த தேதி',
    dob: 'பிறந்த தேதி',
    phoneNo: 'தொலைபேசி எண்',
    address: 'முகவரி',
    prev: 'கடந்த',
    next: 'அடுத்தது',
    submit: 'சமர்ப்பிக்கவும்',
    yes: 'ஆம்',
    no: 'இல்லை',
    other: 'மற்றவை',
    trust: 'அமைப்பு',
    waitForConfirmation: 'உறுதிப்படுத்தலுக்காக காத்திருக்கிறது',
    alreadyRegistered: 'ஏற்கனவே பதிவு செய்யப்பட்டது',
    goBack: 'திரும்பிச் செல்லுங்கள்',
    goToLogin: 'உள்நுழைய மீண்டும் செல்லவும்',
    retryAgain: 'மீண்டும் முயற்சிக்கவும்',
    congrats: 'வாழ்த்துக்கள்',
    sorry: 'மன்னிக்கவும்',
    chat: 'அரட்டை',
    logout: 'வெளியேறு',
    changeLang: 'மொழியை மாற்றவும்',
    settings: 'அமைப்புகள்',
    password: 'கடவுச்சொல்',
    retypePassword: 'கடவுச்சொல்லை மீண்டும் தட்டச்சு செய்க',
    email: 'மின்னஞ்சல்',
    specializedIn: 'சிறப்பு',
    home: 'வாசஸ்தலம்',
    history: 'வரலாறு',
    upcomingNotifications: 'வரவிருக்கும் அறிவிப்புகள்',
    noNotificaionsAvailable: 'அறிவிப்புகள் எதுவும் கிடைக்கவில்லை!',
    profile: 'சுயவிவரம்',
    company: 'நிறுவனம்',
    app: 'செயலி',
    account: 'கணக்கு',
    appointments: 'நியமனங்கள்',
    aboutUs: 'எங்களை பற்றி',
    faq: 'எஃப்.ஏ.கே.',
    termsConditions: 'விதிமுறைகளும் நிபந்தனைகளும்',
    privacyPolicies: 'தனியுரிமைக் கொள்கைகள்',
    language: 'மொழி',
    aboutApp: 'செயலி பற்றி',
    questions: [
      {question: 'கேட்க சில நல்ல கேள்விகள் யாவை?', options: taOptions },
      {question: 'கேட்க 10 கேள்விகள் யாவை?', options: taOptions },
      {question: '36 கேள்விகள் யாவை?', options: taOptions },
      {question: 'சில ஆழமான உறவு கேள்விகள் யாவை?', options: taOptions },
      {question: 'எனது ஈர்ப்பை நான் என்ன கேள்விகளைக் கேட்க முடியும்?', options: taOptions },
      {question: 'என் பெண் நண்பரிடம் நான் என்ன கேட்க வேண்டும்?', options: taOptions },
    ],
  }
};
