export const colors = {
  primary: "#fbc341",
  white: "#ffffff",
  black: "#000000",
  dander: "#f00000",
  success: "#00f055",
};

export const baseURL = "http://51.210.150.124:8088/";

export const options = [
  { name: "Yes", value: "yes" },
  { name: "No", value: "no" },
  // {name: 'Other', value: 'other'},
];

export const taOptions = [
  { name: "ஆம்", value: "yes" },
  { name: "இல்லை", value: "no" },
  // {name: 'மற்றவை', value: 'other'},
];

export const language = {
  en: {
    login: "Login",
    register: "Register",
    lorem20:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    skip: "Skip",
    auth: "Auth",
    chooseOne: "Choose One",
    parent: "Parent",
    physician: "Physician",
    features: "Features",
    dashboard: "Dashboard",
    aboutApp: "About App",
    questionnaire: "Questionnaire",
    onboarding: "Onboarding",
    firstName: "First Name",
    lastName: "Last Name",
    babyName: "Baby Name",
    babyDob: "Baby Date of Birth",
    dob: "Date of Birth",
    phoneNo: "Phone Number",
    address: "Address",
    prev: "Prev",
    next: "Next",
    submit: "Submit",
    yes: "Yes",
    no: "No",
    other: "Other",
    trust: "Trust",
    waitForConfirmation: "Waiting for confirmation",
    alreadyRegistered: "Already Registered",
    goBack: "Go Back",
    goToLogin: "Go to Login",
    retryAgain: "Retry again",
    congrats: "Congrats",
    sorry: "Sorry",
    chat: "Chat",
    logout: "Logout",
    changeLang: "Change Language",
    settings: "Settings",
    password: "Password",
    retypePassword: "Retype Password",
    email: "Email",
    specializedIn: "Specialized In",
    home: "Home",
    history: "History",
    upcomingNotifications: "Upcoming Notifications",
    noNotificaionsAvailable: "No notifications available!",
    profile: "Profile",
    company: "Company",
    app: "App",
    account: "Account",
    appointments: "Appointments",
    aboutUs: "About Us",
    faq: "F.A.Q.",
    termsConditions: "Terms & Conditions",
    privacyPolicies: "Privacy Policies",
    language: "Language",
    state: "State",
    district: "District",
    city: "City",
    country: "Country",
    pincode: "Pincode",
    checkNow: "Check Now",
    done: "Done",
    visitors: "Visitors",
    visitor: "Visitor",
    os: "Operating System",
    appVersion: "Application Version",
    legal: "Legal Information",
    hello: "Hello",
    lets: "Let's make this simple.",
    about: `Satya's long journey has been an arduous one but a heart-warming one at the same time. In addition to being trailblazers in the domain of disability management, today Satya spearheads a number of unique initiatives in and around Puducherry. At present, it caters to over 900 children with special needs through its seven urban and three rural centres. Its mobile therapy crew provides door-to-door service to over 124 disabled children living in Puducherry's 44 fringe localities.`,
    questions: [
      { question: "What are some good questions to ask?", options },
      { question: "What are 10 questions to ask?", options },
      { question: "What are the 36 questions?", options },
      { question: "What are some deep relationship questions?", options },
      { question: "What questions can I ask my crush?", options },
      { question: "What should I ask my gf?", options },
    ],
    terms: [
      `Help protect your website and its users with clear and fair website terms and conditions. These terms and conditions for a website set out key issues such as acceptable use, privacy, cookies, registration and passwords, intellectual property, links to other sites, termination and disclaimers of responsibility. Terms and conditions are used and necessary to protect a website owner from liability of a user relying on the information or the goods provided from the site then suffering a loss.`,
      `Making your own terms and conditions for your website is hard, not impossible, to do. It can take a few hours to few days for a person with no legal background to make. We are here to help you out.`,
      `All you need to do is fill up the blank spaces and then you will receive an email with your personalized terms and conditions.`,
    ],
    policy: [
      `Help protect your website and its users with clear and fair website terms and conditions. These terms and conditions for a website set out key issues such as acceptable use, privacy, cookies, registration and passwords, intellectual property, links to other sites, termination and disclaimers of responsibility. Terms and conditions are used and necessary to protect a website owner from liability of a user relying on the information or the goods provided from the site then suffering a loss.`,
      `Making your own terms and conditions for your website is hard, not impossible, to do. It can take a few hours to few days for a person with no legal background to make. We are here to help you out.`,
      `All you need to do is fill up the blank spaces and then you will receive an email with your personalized terms and conditions.`,
    ],
  },
  ta: {
    login: "உள்நுழைய",
    register: "பதிவு செய்ய",
    lorem20:
      "லோரெம் இப்சம் என்பது அச்சிடுதல் மற்றும் தட்டச்சு செய்யும் துறையின் போலி உரை.",
    skip: "தவிர்",
    auth: "அங்கீகாரம்",
    chooseOne: "ஒன்றை தேர்ந்தெடு",
    parent: "பெற்றோர்",
    physician: "மருத்துவர்",
    features: "அம்சங்கள்",
    dashboard: "டாஷ்போர்டு",
    questionnaire: "கேள்வித்தாள்",
    onboarding: "போர்ட்போர்டிங்",
    firstName: "முதல் பெயர்",
    lastName: "கடைசி பெயர்",
    babyName: "குழந்தை பெயர்",
    babyDob: "குழந்தை பிறந்த தேதி",
    dob: "பிறந்த தேதி",
    phoneNo: "தொலைபேசி எண்",
    address: "முகவரி",
    prev: "கடந்த",
    next: "அடுத்தது",
    submit: "சமர்ப்பிக்கவும்",
    yes: "ஆம்",
    no: "இல்லை",
    other: "மற்றவை",
    trust: "அமைப்பு",
    waitForConfirmation: "உறுதிப்படுத்தலுக்காக காத்திருக்கிறது",
    alreadyRegistered: "ஏற்கனவே பதிவு செய்யப்பட்டது",
    goBack: "திரும்பிச் செல்லுங்கள்",
    goToLogin: "உள்நுழைய மீண்டும் செல்லவும்",
    retryAgain: "மீண்டும் முயற்சிக்கவும்",
    congrats: "வாழ்த்துக்கள்",
    sorry: "மன்னிக்கவும்",
    chat: "அரட்டை",
    logout: "வெளியேறு",
    changeLang: "மொழியை மாற்றவும்",
    settings: "அமைப்புகள்",
    password: "கடவுச்சொல்",
    retypePassword: "கடவுச்சொல்லை மீண்டும் தட்டச்சு செய்க",
    email: "மின்னஞ்சல்",
    specializedIn: "சிறப்பு",
    home: "வாசஸ்தலம்",
    history: "வரலாறு",
    upcomingNotifications: "வரவிருக்கும் அறிவிப்புகள்",
    noNotificaionsAvailable: "அறிவிப்புகள் எதுவும் கிடைக்கவில்லை!",
    profile: "சுயவிவரம்",
    company: "நிறுவனம்",
    app: "செயலி",
    account: "கணக்கு",
    appointments: "நியமனங்கள்",
    aboutUs: "எங்களை பற்றி",
    faq: "எஃப்.ஏ.கே.",
    termsConditions: "விதிமுறைகளும் நிபந்தனைகளும்",
    privacyPolicies: "தனியுரிமைக் கொள்கைகள்",
    language: "மொழி",
    aboutApp: "செயலி பற்றி",
    state: "மாநிலம்",
    city: "நகரம்",
    district: "மாவட்டம்",
    country: "நாடு",
    pincode: "அஞ்சல் குறியீடு",
    checkNow: "இப்போது சரிபார்க்க",
    done: "முடிந்தது",
    visitors: "பார்வையாளர்கள்",
    visitor: "பார்வையாளர்",
    os: "இயக்க முறைமை",
    appVersion: "விண்ணப்ப பதிப்பு",
    legal: "சட்ட தகவல்",
    hello: "ஹலோ",
    lets: "இதை எளிதாக்குவோம்.",
    about: `சத்யாவின் நீண்ட பயணம் கடினமான ஒரு பயணமாக இருந்தது, ஆனால் அதே நேரத்தில் இதயத்தை வெப்பமாக்குகிறது. இயலாமை மேலாண்மை களத்தில் டிரெயில்ப்ளேஸர்களாக இருப்பதோடு மட்டுமல்லாமல், இன்று புதுச்சேரி மற்றும் அதைச் சுற்றியுள்ள பல தனித்துவமான முயற்சிகளை சத்யா முன்னெடுத்து வருகிறார். தற்போது, அதன் ஏழு நகர்ப்புற மற்றும் மூன்று கிராமப்புற மையங்கள் மூலம் சிறப்புத் தேவைகளைக் கொண்ட 900 க்கும் மேற்பட்ட குழந்தைகளை இது வழங்குகிறது. புதுச்சேரியின் 44 விளிம்பு வட்டாரங்களில் வசிக்கும் 124 க்கும் மேற்பட்ட ஊனமுற்ற குழந்தைகளுக்கு அதன் மொபைல் சிகிச்சை குழு வீடு வீடாக சேவை வழங்குகிறது.`,
    questions: [
      { question: "கேட்க சில நல்ல கேள்விகள் யாவை?", options: taOptions },
      { question: "கேட்க 10 கேள்விகள் யாவை?", options: taOptions },
      { question: "36 கேள்விகள் யாவை?", options: taOptions },
      { question: "சில ஆழமான உறவு கேள்விகள் யாவை?", options: taOptions },
      {
        question: "எனது ஈர்ப்பை நான் என்ன கேள்விகளைக் கேட்க முடியும்?",
        options: taOptions,
      },
      {
        question: "என் பெண் நண்பரிடம் நான் என்ன கேட்க வேண்டும்?",
        options: taOptions,
      },
    ],
    terms: [
      `தெளிவான மற்றும் நியாயமான வலைத்தள விதிமுறைகள் மற்றும் நிபந்தனைகளுடன் உங்கள் வலைத்தளத்தையும் அதன் பயனர்களையும் பாதுகாக்க உதவுங்கள். ஒரு வலைத்தளத்திற்கான இந்த விதிமுறைகள் மற்றும் நிபந்தனைகள் ஏற்றுக்கொள்ளக்கூடிய பயன்பாடு, தனியுரிமை, குக்கீகள், பதிவு மற்றும் கடவுச்சொற்கள், அறிவுசார் சொத்து, பிற தளங்களுக்கான இணைப்புகள், பணிநீக்கம் மற்றும் பொறுப்பு மறுப்பு போன்ற முக்கிய சிக்கல்களை அமைக்கின்றன. வலைத்தள உரிமையாளரை தகவல் அல்லது தளத்திலிருந்து வழங்கப்பட்ட பொருட்களை நம்பியிருக்கும் பயனரின் பொறுப்பிலிருந்து பாதுகாக்க விதிமுறைகள் மற்றும் நிபந்தனைகள் பயன்படுத்தப்படுகின்றன, பின்னர் இழப்பை சந்திக்கின்றன.`,
      `உங்கள் வலைத்தளத்திற்கான உங்கள் சொந்த விதிமுறைகளையும் நிபந்தனைகளையும் உருவாக்குவது கடினம், சாத்தியமற்றது அல்ல. சட்ட பின்னணி இல்லாத ஒரு நபரை உருவாக்க சில மணிநேரங்கள் முதல் சில நாட்கள் வரை ஆகலாம். உங்களுக்கு உதவ நாங்கள் இங்கு வந்துள்ளோம்.`,
      `நீங்கள் செய்ய வேண்டியது வெற்று இடங்களை நிரப்புவது மட்டுமே, பின்னர் உங்கள் தனிப்பயனாக்கப்பட்ட விதிமுறைகள் மற்றும் நிபந்தனைகளுடன் ஒரு மின்னஞ்சலைப் பெறுவீர்கள்.`,
    ],
    policy: [
      `தெளிவான மற்றும் நியாயமான வலைத்தள விதிமுறைகள் மற்றும் நிபந்தனைகளுடன் உங்கள் வலைத்தளத்தையும் அதன் பயனர்களையும் பாதுகாக்க உதவுங்கள். ஒரு வலைத்தளத்திற்கான இந்த விதிமுறைகள் மற்றும் நிபந்தனைகள் ஏற்றுக்கொள்ளக்கூடிய பயன்பாடு, தனியுரிமை, குக்கீகள், பதிவு மற்றும் கடவுச்சொற்கள், அறிவுசார் சொத்து, பிற தளங்களுக்கான இணைப்புகள், பணிநீக்கம் மற்றும் பொறுப்பு மறுப்பு போன்ற முக்கிய சிக்கல்களை அமைக்கின்றன. வலைத்தள உரிமையாளரை தகவல் அல்லது தளத்திலிருந்து வழங்கப்பட்ட பொருட்களை நம்பியிருக்கும் பயனரின் பொறுப்பிலிருந்து பாதுகாக்க விதிமுறைகள் மற்றும் நிபந்தனைகள் பயன்படுத்தப்படுகின்றன, பின்னர் இழப்பை சந்திக்கின்றன.`,
      `உங்கள் வலைத்தளத்திற்கான உங்கள் சொந்த விதிமுறைகளையும் நிபந்தனைகளையும் உருவாக்குவது கடினம், சாத்தியமற்றது அல்ல. சட்ட பின்னணி இல்லாத ஒரு நபரை உருவாக்க சில மணிநேரங்கள் முதல் சில நாட்கள் வரை ஆகலாம். உங்களுக்கு உதவ நாங்கள் இங்கு வந்துள்ளோம்.`,
      `நீங்கள் செய்ய வேண்டியது வெற்று இடங்களை நிரப்புவது மட்டுமே, பின்னர் உங்கள் தனிப்பயனாக்கப்பட்ட விதிமுறைகள் மற்றும் நிபந்தனைகளுடன் ஒரு மின்னஞ்சலைப் பெறுவீர்கள்.`,
    ],
  },
};
